version: "3"
services:
  react-app:
    image: react-app
    build: ./client
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - choice-o-mat-app
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules
  api-server:
    image: api-server
    build: ./server
    env_file: ./server/.env
    ports:
      - "3001:3001"
    networks:
      - choice-o-mat-app
    depends_on:
      - mongo
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
  mongo:
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"
    networks:
      - choice-o-mat-app
    volumes:
      - mongo-data:/data/db
networks:
  choice-o-mat-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
